# Generated by Django 3.2 on 2021-04-20 05:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firt_name', models.CharField(max_length=200)),
                ('middle_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('country_region', models.CharField(max_length=200)),
                ('affiliation', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('corresponding_author', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='KeyWords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keywords', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='PaperInFo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submission_type', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('abstract', models.CharField(max_length=200)),
                ('file', models.FileField(max_length=254, upload_to=None)),
                ('author_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.author')),
                ('keywords', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.keywords')),
            ],
        ),
    ]
